rabbitmq:
  enabled: false
  storage: 5Gi
  cpu: 250m
  memory: 1Gi

kafka:
  replication_factor: 1
  broker:
    replicas: 1
    volume_size: 10Gi
  controller:
    replicas: 1
    volume_size: 10Gi

# For documentation purposes, do not uncomment
# mysql_services: []
# ingress_services: []
# mongodb_services: []

