{{- if eq "java-spring-boot" .Values.type }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostAliases:
        {{- toYaml .Values.host_aliases | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}-app:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.enable_probes }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health_check_path | default "/health" }}
              port: {{ .Values.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.health_check_path | default "/health" }}
              port: {{ .Values.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- end }}

          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}

            # --- MySQL --- #
            {{- if has "mysql" .Values.requires }}
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-{{ .Release.Name }}
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: cloudsql-{{ .Release.Name }}
                  key: port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-{{ .Release.Name }}
                  key: user
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-{{ .Release.Name }}
                  key: pass
            {{- end }}

            # --- RabbitMQ --- #
            {{- if has "rabbitmq" .Values.requires }}
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            {{- end }}

            # --- Redis --- #
            {{- if has "redis" .Values.requires }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: port
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: user
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: pass
            {{- end }}

            # --- User Managed Environment Variables --- #
            {{- range $k := .Values.env }}
            - name: {{ $k.name | quote }}
              value: {{ $k.value | quote }}
            {{- end }}

            # --- User Managed Secrets --- #
            {{- range $s := .Values.secrets }}
            - name: {{ $s }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key:  {{ $s }}
            {{- end }}

{{- end }}
