stages:
  - build

terraform:
  # Only run if it is a downstream pipeline
  rules:
      - if: $CI_PIPELINE_SOURCE == "pipeline"
  image:
    name: hashicorp/terraform:1.12.1
    entrypoint: [""]
  stage: build
  extends: .google-oidc:auth
  variables:
    # NOTE: OIDC variables are provided in the GitLab CI/CD group variables.
    - ENV: ${ENVIRONMENT}

  script:
    - apk add make curl
    # Add GitLab Runner IP to allow for deployments to the GKE cluster
    - export TF_VAR_gitlab_runner_ip=$(curl --ipv4 ifconfig.me)
    - make apply MODULE=infra
    # Apply the Helm charts and related infrastructure
    - make apply MODULE=${SERVICE_GROUP}
    # Remove the GitLab runner IP from being allowed to connect to the cluster
    - export TF_VAR_gitlab_runner_ip=""
    - make apply MODULE=infra

include:
  - remote: 'https://gitlab.com/gitlab-com/gl-security/security-operations/infrastructure-security-public/oidc-modules/-/raw/3.3.0/templates/gcp_auth.yaml'

