stages:
  - build

terraform:
  # Only run if it is a downstream pipeline
  rules:
      - if: $CI_PIPELINE_SOURCE == "pipeline"
  image:
    #name: google/cloud-sdk:latest
    name: hashicorp/terraform:1.12.1
    entrypoint: [""]
  stage: build
  extends: .google-oidc:auth
  variables:
    # NOTE: OIDC variables are provided in the GitLab CI/CD group variables.
  script:
    - apk add make curl
    - export TF_VAR_gitlab_runner_ip=$(curl --ipv4 ifconfig.me)
    - make apply ENV=development LAYER=infra
    - make apply ENV=development LAYER=k8s

include:
  - remote: 'https://gitlab.com/gitlab-com/gl-security/security-operations/infrastructure-security-public/oidc-modules/-/raw/3.3.0/templates/gcp_auth.yaml'

