# === Ingress & Service === #
ingress: false
host: ""
health_check_path: "/health"
security_policy: default

# === Deployment === #
replicas: 2
port: 8080
env: []
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
resources:
  limits:
    cpu: 100m
    ephemeral-storage: 1Gi
    memory: 128Mi
  requests:
    cpu: 50m
    ephemeral-storage: 1Gi
    memory: 64Mi

# === Secrets === #
secrets: []

# === Other === #
migration_type: none
mysql: false
rabbitmq: false

