---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-config
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: redis-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.config_secret }}

