---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: redis-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: redis-config

