apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  ports:
  - name: redis-port
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: redis
    appCluster: redis
  sessionAffinity: None
  type: ClusterIP

