{{ if (not (empty .Values.secrets)) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-env-vars
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-env-vars
    creationPolicy: Owner
    template:
      data:
        # Secrets for the service
        {{- range $k, $v := .Values.secrets }}
        {{ $k }}: "{{"{{."}}{{ $k }}{{ "}}" }}"
        {{- end }}
        # MySQL server test
        {{- if (.Values.mysql) }}
        mysqlRootPassword: "{{`{{.mysqlRootPassword}}`}}"
        {{- end }}
  data:
    {{- range $k, $v := .Values.secrets }}
    {{- if (hasKey $v "from") }}
    - secretKey: {{ $k }}
      remoteRef:
        # ENV_VAR_NAME -> env-var-name
        key: {{ lower $k | replace "_" "-" }}
    {{- else }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $v.from }}
    {{- end }}

    # MySQL server test
    {{- if (.Values.mysql) }}
    - secretKey: mysqlRootPassword
      remoteRef:
        key: {{ .Release.Name }}-mysql-root-password
    {{- end }}
{{ end }} # If secrets is not empty

