{{- if not (empty .Values.secrets) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-redis-credentials
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    template:
      data:
        {{- range $s := .Values.secrets }}
        {{ $v }}: "{{"{{."}}{{ $v }}{{ "}}" }}"
        {{- end }}
  data:
    {{- range $s := .Values.secrets }}
    - secretKey: {{ $s }}
      remoteRef:
        key: {{ $s | replace "_" "-" | lower }}
    {{- end }}
{{- end }}

