{{- if not (empty .Values.secrets) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    template:
      data:
        # === User Managed Secrets === #
        {{- range $s := .Values.secrets }}
        {{ $s }}: "{{"{{."}}{{ $s }}{{ "}}" }}"
        {{- end }}
  data:
    # === User Managed Secrets === #
    {{- range $s := .Values.secrets }}
    - secretKey: {{ $s }}
      remoteRef:
        key: {{ $s | replace "_" "-" | lower }}
    {{- end }}
{{- end }}
{{- if not (empty .Values.redis) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-redis
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-redis
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.serviceGroup }}-{{ .Release.Name }}-redis
{{ end }}

