---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.service_group }}-{{ .Release.Name }}@{{ .Values.project_id }}.iam.gserviceaccount.com

