---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}"}'
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}
spec:
  securityPolicy:
    {{- if .Values.public }}
    name: {{ .Values.security_policy }}-public
    {{- else }}
    name: {{ .Values.security_policy }}
    {{- end }}
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: {{ .Values.health_check_path }}
    port: {{ .Values.port }}

