installCRDs: true
namespaceOverride: external-secrets
fullnameOverride: external-secrets
# Service account is environment-specific
# serviceAccount:
#   annotations:
#     iam.gke.io/gcp-service-account: external-secrets@PROJECT_ID.iam.gserviceaccount.com
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
certController:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
webhook:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

