clusterOperator:
  resources:
    limits:
      memory: 64Mi
      cpu: 50m
    requests:
      memory: 64Mi
      cpu: 50m
msgTopologyOperator:
  resources:
    limits:
      memory: 64Mi
      cpu: 50m
    requests:
      memory: 64Mi
      cpu: 50m

