services:
  nginx:
    image: ${REGION}-docker.pkg.dev/${MANAGEMENT_PROJECT_ID}/${GROUP}/${NAME}-nginx:${VERSION}
    build:
      context: ${SERVICE_DIR}
      dockerfile: ${INFRA_DIR}/docker/node-nginx/Dockerfile
      args:
        - NAME=${NAME}
        - VERSION=${VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - ENVIRONMENT=${ENVIRONMENT}

