services:
  app:
    image: ${REGION}-docker.pkg.dev/${MANAGEMENT_PROJECT_ID}/${GROUP}/${NAME}-app:${VERSION}
    build:
      context: ${SERVICE_DIR}
      dockerfile: ${INFRA_DIR}/docker/vite-react/Dockerfile
      args:
        - NAME=${NAME}
        - VERSION=${VERSION}
        - NODE_VERSION=${NODE_VERSION}

