
%{ if enable_cluster ~}
cluster-enabled yes
cluster-node-timeout 15000
cluster-config-file ${config_file}
%{ else ~}
cluster-enabled no
%{ endif }

appendonly yes
protected-mode yes
dir /data
port ${port}
%{ for k, v in users ~}
user ${k} ~* &* +@all on >${v}
%{ endfor }

