stages:
  - build

terraform:
  image:
    name: google/cloud-sdk:latest
  stage: build
  extends: .google-oidc:auth
  variables:
    # NOTE: OIDC variables are provided in the GitLab CI/CD group variables.
  script:
    - ls -al
    - gcloud storage ls

include:
  - remote: 'https://gitlab.com/gitlab-com/gl-security/security-operations/infrastructure-security-public/oidc-modules/-/raw/3.3.0/templates/gcp_auth.yaml'

