---
# apiVersion: external-secrets.io/v1beta1
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectId }}
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: {{ .Values.region }}
          # name of the GKE cluster
          clusterName: {{ .Values.name }}
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: {{ .Values.projectId }}
          # reference the sa resource name
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

