---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-env-vars
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: keycloak-env-vars
    creationPolicy: Owner
    template:
      data:
        adminPassword: "{{`{{.adminPassword}}`}}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: {{ .Values.service_group }}-keycloak-admin

