{{ if eq .Values.cluster.enabled true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cluster-setup
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
{{ end }}

