---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    iam.gke.io/gcp-service-account: {{ .Values.externalSecretsServiceAccount }}
  name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: default
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.region }}
          clusterName: {{ .Values.name }}
          clusterProjectID: {{ .Values.projectId }}
          # Reference to the service account in Kubernetes
          serviceAccountRef:
            name: external-secrets
            namespace: {{ .Values.serviceGroup }}

