{{ if not (empty .Values.ingressServices) }}
# === Ingress for Service Group === #
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}
    # Build a list of certificates with the service group prefix
    {{- $certificates := list -}}
    {{- range $k, $v := .Values.ingressServices -}}
    {{- $certificates = append $certificates (printf "{{ $.Release.Name }}-%s" $k) -}}
    {{- end -}}
    networking.gke.io/managed-certificates: {{- join "," $certificates | quote -}}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: {{ .Release.Name }}
spec:
  rules:
  {{- range $k, $v := .Values.ingressServices }}
  - host: {{ $v.host | default $k }}.{{ $.Values.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $k }}
            port:
              number: {{ $v.port }}
  {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}
spec:
  sslPolicy: default
  redirectToHttps:
    enabled: true

# === Certificates === #
{{- range $k, $v := .Values.ingressServices }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-{{ $k }}
spec:
  domains:
    - {{ $k }}.{{ .Values.host }}
{{- end }}

{{ end }}

