{{ if not (empty .Values.ingress_services) }}
# === Ingress for Service Group === #
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}
    # Build a list of certificates with the service group prefix
    networking.gke.io/managed-certificates: {{ join "," .Values.certificates }}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: {{ .Release.Name }}
spec:
  rules:
  {{- range $s := .Values.ingress_services }}
  - host: {{ $s.name }}.{{ $.Values.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $s.name }}
            port:
              number: {{ $s.port }}
  {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}
spec:
  sslPolicy: default
  redirectToHttps:
    enabled: true

# === Certificates === #
{{- range $s := .Values.ingress_services }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $.Release.Name }}-{{ $s.name }}
spec:
  domains:
    - {{ $s.name }}.{{ $.Values.host }}
{{- end }}

{{ end }}

