{{- if (len .Values.kafka_services) }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ .Values.service_group }}
spec:
  replicas: {{ .Values.kafka.controller.replicas }}
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.controller.volume_size }}
        kraftMetadata: shared
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: {{ .Values.service_group }}
spec:
  replicas: {{ .Values.kafka.broker.replicas }}
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.broker.volume_size }}
        kraftMetadata: shared
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.service_group }}
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.replication_factor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replication_factor }}
      transaction.state.log.min.isr: {{ .Values.kafka.replication_factor }}
      default.replication.factor: {{ .Values.kafka.replication_factor }}
      min.insync.replicas: {{ .Values.kafka.replication_factor }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}

