{{- if (len .Values.postgresql_services) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsql-pg-root
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: cloudsql-pg-root
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Name }}-cloudsql-pg-root

# === Certificate for the MySQL Server === #
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsql-pg-cert
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: cloudsql-pg-cert
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Release.Name }}-cloudsql-pg-cert

# === Configure Secrets for Each Service === #
{{- range $k := .Values.postgresql_services }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsql-pg-{{ $k }}
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: cloudsql-pg-{{ $k }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Release.Name }}-cloudsql-pg-{{ $k }}
{{- end }}

{{/* Disabled for now, need to get this working still */}}
{{/* For some reason is breaks access for the root user */}}
{{- if false }}
# === Setup SQL User Accounts on the Server === #
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-mysql-init
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-init
        image: mysql:8.0
        # TODO: Don't give all permissions to every user.
        command:
          - /bin/sh
          - -c
          - |
            mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS -e "
            {{- range $k := .Values.mysql_services }}
            CREATE USER IF NOT EXISTS '{{ $k }}'@'%' IDENTIFIED BY '${SVC_PASS_{{ $k }}}';
            GRANT ALL PRIVILEGES ON *.* TO '{{ $k }}'@'%';
            {{- end }}
            GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
            FLUSH PRIVILEGES;
            "
        env:
        # --- Connection info & root credentials --- #
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: cloudsql-pg-root
              key: host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: cloudsql-pg-root
              key: port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-pg-root
              key: user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-pg-root
              key: pass
        # --- User credentials for each service --- #
        {{- range $k := .Values.mysql_services }}
        - name: SVC_PASS_{{ $k }}
          valueFrom:
            secretKeyRef:
              name: cloudsql-pg-{{ $k }}
              key: pass
        {{- end }}
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

{{- end }}
{{- end }}

