name: Build & Deploy Service


on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service"
        required: true
        type: string
      service_group:
        description: "Name of the service group to deploy"
        required: true
        type: string
      environment:
        description: "Environment to make the deployment to"
        required: true
        type: string
      ref:
        required: true
        type: string


permissions:
  id-token: write
  contents: read


jobs:

  matrix:
    name: "🔧 Prepare Build Matrix"
    runs-on: ubuntu-latest
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Roamtech-Solutions/infrastructure
          ref: master
          token: ${{ secrets.INFRA_PAT }}
          path: infrastructure
      - name: Load build matrix
        id: setup
        run: |
          service_type=$(yq '.type' ./${{ github.event.repository.name }}/env/${{ inputs.environment }}.yaml)
          test -n "${service_type}"
          echo matrix=$(cat infrastructure/.github/matrix/docker-${service_type}.json | tr -d '\n' | tr -d '\t') >> $GITHUB_OUTPUT
          echo tag="${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
      tag: ${{ steps.setup.outputs.tag }}


  # === Build === #
    
  build:
    name: "🐳📦 ${{ inputs.service_name }}-${{ matrix.name }}:${{ needs.matrix.outputs.tag }}"
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Roamtech-Solutions/infrastructure
          ref: master
          token: ${{ secrets.INFRA_PAT }}
          path: infrastructure
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Prepare Docker build
        run: |
          cp -r infrastructure/docker ${{ github.event.repository.name }}
      - name: Google Cloud Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 416.0.0'
      - name: GCR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.event.repository.name }}
          file: ${{ github.event.repository.name }}/${{ matrix.dockerfile }}
          push: true
          tags: "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.MANAGEMENT_PROJECT_ID }}/${{ inputs.service_group }}/${{ inputs.service_name }}-${{ matrix.name }}:${{ needs.matrix.outputs.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max


  # === Deployment === #

  deploy:
    name: "Deploy ${{ inputs.service_name }}:${{ needs.matrix.outputs.tag }}"
    runs-on: ubuntu-latest
    needs:
      - build
      - matrix
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:

      # --- Setup --- #
      - name: Checkout caller repository
        uses: actions/checkout@v4
      - name: Google Cloud Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 416.0.0'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"

      # --- Upload values file --- #
      - name: Update values
        run: |
          export SERVICE_NAME=${{ inputs.service_name }}
          echo tag: ${{ needs.matrix.outputs.tag }} > /tmp/values.yaml
          envsubst < ./env/${{ inputs.environment }}.yaml >> /tmp/values.yaml
          cat /tmp/values.yaml
          gcloud storage cp /tmp/values.yaml gs://${{ env.MANAGEMENT_PROJECT_ID }}-values/${{ inputs.environment }}/${{ inputs.service_group }}/${{ inputs.service_name }}.yaml

      # --- Apply Terraform --- #
#      - name: Checkout infrastructure repository
#        uses: actions/checkout@v4
#        with:
#          repository: Roamtech-Solutions/infrastructure
#          ref: master
#          token: ${{ secrets.INFRA_PAT }}
#      # Authenticate again because the checkout deletes the credentials file
#      - name: Google Cloud Authentication
#        uses: 'google-github-actions/auth@v2'
#        with:
#          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
#          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
#          create_credentials_file: true
#      - name: Terraform
#        run: |
#          sudo apt update
#          sudo apt install -y make curl
#
#          # Add GitLab Runner IP to allow for deployments to the GKE cluster.
#          export TF_VAR_ci_runner_ip=$(curl --ipv4 ifconfig.me)
#          make apply ENV=${{ inputs.environment }} MOD=infra
#
#          # Apply the Helm charts and related infrastructure for the service
#          # group.
#          make apply ENV=${{ inputs.environment }} \
#            MOD=service-group \
#            SG=${{ inputs.service_group }}
#
#          # Remove the GitLab runner IP from being allowed to connect to the
#          # cluster.
#          export TF_VAR_ci_runner_ip=""
#          make apply ENV=${{ inputs.environment }} MOD=infra
#
