name: Build & Deploy Service


on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service"
        required: true
        type: string
      service_group:
        description: "Name of the service group to deploy"
        required: true
        type: string
      environment:
        description: "Environment to make the deployment to"
        required: true
        type: string
      ref:
        required: true
        type: string


permissions:
  id-token: write
  contents: read


jobs:

  matrix:
    timeout-minutes: 15
    name: "🔧 Prepare Build Matrix"
    runs-on: arc-runner-set
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Roamtech-Solutions/infrastructure
          ref: master
          token: ${{ secrets.INFRA_PAT }}
          path: infrastructure
      - name: Load build matrix
        id: setup
        run: |
          # --- Install Dependencies --- #
          sudo apt update 
          sudo apt install -y jq wget
          wget https://github.com/mikefarah/yq/releases/download/v4.47.1/yq_linux_amd64.tar.gz -O - |\
            tar xz && sudo mv yq_linux_amd64 /usr/local/bin/yq

          service_type=$(yq '.type' ./${{ github.event.repository.name }}/env/${{ inputs.environment }}.yaml)
          test -n "${service_type}"

          # --- Docker images to build --- #
          echo matrix=$(cat infrastructure/.github/matrix/docker-${service_type}.json | tr -d '\n' | tr -d '\t') >> $GITHUB_OUTPUT

          # --- Java Version --- #
          test -f ${{ github.event.repository.name }}/pom.xml \
            && echo java_version=$(grep -oP '(?<=<java.version>).*?(?=</java.version>)' ${{ github.event.repository.name }}/pom.xml) >> $GITHUB_OUTPUT \
            || echo java_version=17 >> $GITHUB_OUTPUT

          # --- PHP Version --- #
          test -f ${{ github.event.repository.name }}/composer.json \
            && echo php_version=$(jq -r '.require.php' ${{ github.event.repository.name }}/composer.json | grep -o '[0-9.]\+') >> $GITHUB_OUTPUT \
            || echo php_version=8.4 >> $GITHUB_OUTPUT

          # --- Go Version --- #
          test -f ${{ github.event.repository.name }}/go.mod \
            && eval $(echo go_version=$(grep -E '^go ' ${{ github.event.repository.name }}/go.mod | cut -d' ' -f 2) | tee -a $GITHUB_OUTPUT) \
            || eval $(echo go_version=1.23.0 | tee -a $GITHUB_OUTPUT)

          # --- Go Run Image --- #
          # Some dependencies mean that we can't build static binaries, such as v8go.
          # In this case CGO_ENABLED is set to 1 and another image is used.
          test -f ${{ github.event.repository.name }}/go.mod \
            && grep -e 'v8go' ${{ github.event.repository.name }}/go.mod \
            && ( \
              echo "go_run_image=golang:${go_version}" >> $GITHUB_OUTPUT \
              && echo "cgo_enabled=1" >> $GITHUB_OUTPUT \
            ) || ( \
              echo "go_run_image=alpine:latest" >> $GITHUB_OUTPUT \
              && echo "cgo_enabled=0" >> $GITHUB_OUTPUT \
            )

          # --- Node Version --- #
          test -f ${{ github.event.repository.name }}/package.json \
            && node_version=$( \
              jq -r '.engines.node // "24" | match("[0-9]+(\\.[0-9]+)?(\\.[0-9]+)?"; "g") | last(.).string' \
              ${{ github.event.repository.name }}/package.json | tail -1 \
            ) \
            && echo "node_version=${node_version}" >> $GITHUB_OUTPUT \
            || echo "node_version=24" >> $GITHUB_OUTPUT

          # --- Node Build Directory --- #
          # We have VueJS or React applications. If 'react' is in the package.json, assume that it is a React Application.
          test -f ${{ github.event.repository.name }}/package.json \
            && grep 'react' ${{ github.event.repository.name }}/package.json > /dev/null 2>&1 \
            && node_build_dir=build/client \
            || node_build_dir=dist

          # Explicit override in the environment yaml
          node_build_dir_override=$(grep -E '^node_build_dir:' ${{ github.event.repository.name }}/env/${{ inputs.environment }}.yaml | sed 's/node_build_dir: //g')
          if [ -n "${node_build_dir_override}" ]; then
            node_build_dir=${node_build_dir_override}
          fi

          echo "node_build_dir=${node_build_dir}" >> $GITHUB_OUTPUT

          # --- Python Version --- #
          python_version=$(grep -E '^python_version:' ${{ github.event.repository.name }}/env/${{ inputs.environment }}.yaml | sed 's/python_version: //g')
          if [ -z "${python_version}" ]; then
            python_version=3.10
          fi
          echo "python_version=${python_version}" >> $GITHUB_OUTPUT


    outputs:
      go_version: ${{ steps.setup.outputs.go_version }}
      cgo_enabled: ${{ steps.setup.outputs.cgo_enabled }}
      go_run_image: ${{ steps.setup.outputs.go_run_image }}
      java_version: ${{ steps.setup.outputs.java_version }}
      php_version: ${{ steps.setup.outputs.php_version }}
      node_version: ${{ steps.setup.outputs.node_version }}
      node_build_dir: ${{ steps.setup.outputs.node_build_dir }}
      python_version: ${{ steps.setup.outputs.python_version }}
      matrix: ${{ steps.setup.outputs.matrix }}


  # === Build === #
    
  build:
    timeout-minutes: 15
    name: "🐳📦 ${{ inputs.service_name }}-${{ matrix.name }}:${{ inputs.ref }}"
    # Using managed runners for builds, because GKE autopilot doesn't support 
    # Docker in Docker.
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Roamtech-Solutions/infrastructure
          ref: master
          token: ${{ secrets.INFRA_PAT }}
          path: infrastructure
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Prepare Docker build
        run: |
          cp -r infrastructure/docker ${{ github.event.repository.name }}
      - name: Google Cloud Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
          access_token_lifetime: 3600s
      - name: Setup Google Cloud SDK
        run: |
          sudo apt update && sudo apt install -y wget
          wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
          tar -xzf google-cloud-cli-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh --quiet
          ./google-cloud-sdk/bin/gcloud --version

      - name: GCR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
      - name: Dockerginore
        run: |
          echo ".git" >> ${{ github.event.repository.name }}/.dockerignore
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.event.repository.name }}
          file: ${{ github.event.repository.name }}/${{ matrix.dockerfile }}
          push: false
          load: true
          tags: "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.MANAGEMENT_PROJECT_ID }}/${{ inputs.service_group }}/${{ inputs.service_name }}-${{ matrix.name }}:${{ inputs.ref }}"
          build-args: |
            NAME=${{ inputs.service_name }}
            VERSION=${{ inputs.ref }}
            ENVIRONMENT=${{ inputs.environment }}
            JAVA_VERSION=${{ needs.matrix.outputs.java_version }}
            PYTHON_VERSION=${{ needs.matrix.outputs.python_version }}
            PHP_VERSION=${{ needs.matrix.outputs.php_version }}
            NODE_VERSION=${{ needs.matrix.outputs.node_version }}
            NODE_BUILD_DIR=${{ needs.matrix.outputs.node_build_dir }}
            GO_VERSION=${{ needs.matrix.outputs.go_version }}
            CGO_ENABLED=${{ needs.matrix.outputs.cgo_enabled }}
            GO_RUN_IMAGE=${{ needs.matrix.outputs.go_run_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Google Cloud Authentication
        id: reauth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
          access_token_lifetime: 3600s
      - name: GCR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.reauth.outputs.auth_token }}
      - name: Docker Push
        run: |
          docker push ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.MANAGEMENT_PROJECT_ID }}/${{ inputs.service_group }}/${{ inputs.service_name }}-${{ matrix.name }}:${{ inputs.ref }}
  # === Deployment === #

  deploy:
    timeout-minutes: 15
    name: "Deploy ${{ inputs.service_name }}:${{ inputs.ref }}"
    runs-on: arc-runner-set
    needs:
      - build
      - matrix
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:

      # --- Setup --- #
      - name: Dependencies
        run: |
          sudo apt update && sudo apt install -y wget gettext make
          wget https://github.com/mikefarah/yq/releases/download/v4.47.1/yq_linux_amd64.tar.gz -O - |\
            tar xz && sudo mv yq_linux_amd64 /usr/local/bin/yq
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Roamtech-Solutions/infrastructure
          ref: master
          token: ${{ secrets.INFRA_PAT }}
          path: infrastructure
      - name: Google Cloud Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
      - name: Setup Google Cloud SDK
        run: |
          wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
          tar -xzf google-cloud-cli-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh --quiet
          ./google-cloud-sdk/bin/gcloud --version
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"
      # --- Upload values file --- #
      - name: Update values
        run: |
          export SERVICE_NAME=${{ inputs.service_name }}
          export ENVIRONMENT=${{ inputs.environment }}

          cd ${{ github.event.repository.name }}

          # --- Image Tag --- #
          echo tag: ${{ inputs.ref }} > /tmp/values.yaml

          # --- Environment --- #
          echo environment: ${{ inputs.environment }} >> /tmp/values.yaml

          # --- Service Port --- #
          service_type=$(yq '.type' ./env/${{ inputs.environment }}.yaml)
          test -n "${service_type}"
          case "${service_type}" in
            "wordpress") echo "port: 80" >> /tmp/values.yaml;;
            "node-nginx") echo "port: 80" >> /tmp/values.yaml;;
            "node-next") echo "port: 3000" >> /tmp/values.yaml;;
            *) grep -E '^port:' ./env/${{ inputs.environment }}.yaml || echo "port: 8080" >> /tmp/values.yaml;;
          esac

          # --- Migration Type --- #
          
          if grep 'migration_type: ' ./env/${{ inputs.environment }}.yaml > /dev/null 2>&1; then
            # Migration type already set
            migration_type=$(grep 'migration_type: ' ./env/${{ inputs.environment }}.yaml | sed 's/migration_type: //g')
            echo "migration type: ${migration_type}"
          else
            # Set the migration type, if needed
            # PHP Laravel
            test -f artisan && test -d database/migrations \
              && echo "migration_type: artisan" >> /tmp/values.yaml
            # PHP Phinx
            test -f phinx.php && test -d db/migrations \
              && echo "migration_type: phinx" >> /tmp/values.yaml
            # Python Django
            test -f manage.py \
              && echo "migration_type: django" >> /tmp/values.yaml
          fi

          # --- Configured Values --- #
          envsubst < ./env/${{ inputs.environment }}.yaml >> /tmp/values.yaml

          cd -

          # --- Upload --- #
          ./google-cloud-sdk/bin/gcloud storage cp /tmp/values.yaml \
            gs://${{ env.MANAGEMENT_PROJECT_ID }}-values/${{ inputs.environment }}/${{ inputs.service_group }}/${{ inputs.service_name }}.yaml

      # --- Apply Terraform --- #
      - name: Terraform
        run: |
          # Apply the Helm charts and related infrastructure for the service
          # group.
          cd infrastructure
          make apply ENV=${{ inputs.environment }} \
            MOD=service-group \
            SG=${{ inputs.service_group }}

