name: Deploy Service
on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service"
        required: true
        type: string
      service_group:
        description: "Name of the service group to deploy"
        required: true
        type: string
      environment:
        description: "Environment to make the deployment to"
        required: true
        type: string
      ref:
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: "Deploy ${{ inputs.service_name }}:${{ inputs.ref }}"
    runs-on: ubuntu-latest
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      # === Setup === #
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Google Cloud Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 416.0.0'
      - name: GCR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"

      # === Deploy values file === #
      - name: Update values
        run: |
          export SERVICE_NAME=${{ inputs.service_name }}
          envsubst < ./helm/${{ inputs.environment }}.yaml > /tmp/values.yaml
          cat /tmp/values.yaml
          gcloud storage cp /tmp/values.yaml gs://${{ env.MANAGEMENT_PROJECT_ID }}-values/${{ inputs.environment }}/${{ inputs.service_group }}/${{ inputs.service_name }}.yaml

      # === Apply Terraform === #
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
      - name: Terraform
        run: |
          apk add make curl

          # Add GitLab Runner IP to allow for deployments to the GKE cluster.
          export TF_VAR_gitlab_runner_ip=$(curl --ipv4 ifconfig.me)
          make apply ENV=${{ inputs.environment }} MODULE=infra

          # Apply the Helm charts and related infrastructure for the service
          # group.
          make apply ENV=${{ inputs.environment }} \
            MODULE=${{ inputs.service_group }}

          # Remove the GitLab runner IP from being allowed to connect to the
          # cluster.
          export TF_VAR_gitlab_runner_ip=""
          make apply ENV=${{ inputs.environment }} MODULE=infra

