name: Deploy Service Group
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      service_group:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
          - development
        required: true
      service_group:
        type: choice
        description: Service Group to deploy
        options: 
          - adenzo
          - emalify
          - data
          - imt
          - payments
          - tumatuma
          - ecommerce
        required: true
jobs:
  install:
    name: Deploy - ${{ inputs.environment }} - ${{ inputs.service_group }}
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    runs-on: arc-runner-set
    env:
      # NOTE: Values hardcoded here because you need GitHub enterprise to set
      #       these at the org level.
      MANAGEMENT_PROJECT_ID: management-b6d6
      GOOGLE_CLOUD_WIP: 'projects/155168468510/locations/global/workloadIdentityPools/github/providers/github-provider'
      GAR_REGION: europe-west1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Google Cloud Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.MANAGEMENT_PROJECT_ID }}
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WIP }}
          create_credentials_file: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Dependencies
        run: |
          sudo apt update && sudo apt install -y make
      - name: Install Service Group
        run: |
          make apply ENV=${{ inputs.environment }} MOD=service-group SG=${{ inputs.service_group }}

